# Built with Jekyll 3.2.0

# Setup
title:               Music of the Spheres.
tagline:             'Space Cartography'
description:         'In this site, I will document my research progress.'
url:                 'http://minicomp.github.io'
baseurl:             '/universe-map'

# About/contact
author:
  name:              Ramiro Leal-Cavazos
  url:               https://twitter.com/ramlealc
  email:             ramiro2@stanford.edu

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
